### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by DamirSvrtan** [m1foley/fit-commit#1]
I've installed fit-commit and tried to commit:

``` shell
/Users/damirsvrtan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fit-commit-1.0.1/lib/fit-commit/runner.rb:72:in `initialize': No such file or directory @ rb_sysopen -  (Errno::ENOENT)
    from /Users/damirsvrtan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fit-commit-1.0.1/lib/fit-commit/runner.rb:72:in `open'
    from /Users/damirsvrtan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fit-commit-1.0.1/lib/fit-commit/runner.rb:72:in `message_text'
    from /Users/damirsvrtan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fit-commit-1.0.1/lib/fit-commit/runner.rb:68:in `relevant_message_lines'
    from /Users/damirsvrtan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fit-commit-1.0.1/lib/fit-commit/runner.rb:64:in `lines'
    from /Users/damirsvrtan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fit-commit-1.0.1/lib/fit-commit/runner.rb:80:in `empty_commit?'
    from /Users/damirsvrtan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fit-commit-1.0.1/lib/fit-commit/runner.rb:17:in `run'
    from /Users/damirsvrtan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fit-commit-1.0.1/lib/fit-commit.rb:5:in `run'
    from -e:11:in `<main>'
```

**Comment by m1foley** [comment]
`.git/hooks/commit-msg` is supposed to be called with an argument that represents the path to the commit message (usually `.git/COMMIT_EDITMSG`). That appears not to have been provided.

I'd like to find out why this is broken.

- What editor were you using to write the commit message?
- Did you invoke it by simply calling `git commit` on the command line?
- Does this error also occur when you use `git commit -m "foo"`?
- When you're in the middle of writing your commit (i.e., before you save) does the `.git/COMMIT_EDITMSG` file exist in your Git repo? 
- Can you open your `.git/hooks/commit-msg` and insert this line somewhere to tell me how it's being called? `echo "debug1: $0 $*"`

**Comment by m1foley** [comment]
Rather than inserting that `echo`, you can instead run `gem update fit-commit` and try running it again. It now handles this error case and outputs that relevant information.

**Comment by bf4** [comment]
:+1:
