### ISSUE TITLE
gitlint

### ISSUE THREAD

**Issue by jorisroovers** [m1foley/fit-commit#14]
It seems sir, that we had a very similar idea at a very similar time. I've had this in mind for a while, but started working on gitlint last week: https://github.com/jorisroovers/gitlint. 

Still very early stages like fit-commit, but I think we can probably learn from one another and share some ideas/code :)

**Comment by m1foley** [comment]
Looks great! I'll link to it in the Fit Commit README. We'll team up to eliminate Git log crimes ;)
