### ISSUE TITLE
Apparent hang until hitting enter again

### ISSUE THREAD

**Issue by le-dhogan** [m1foley/fit-commit#16]
Nice work @m1foley 

I've noticed something strange when running under MINGW32.

From the prompt if I commit using `git commit -m "Fixes Something"` and hit enter I get what appears to be a hang. It's not until I hit enter for a second time I see the results of fit-commit.

Here's a screen after hitting enter
![image](https://cloud.githubusercontent.com/assets/7531954/9787202/7be6fe34-57b8-11e5-8998-1180d22dcb44.png)

Here's a screen after hitting enter for a second time.
![image](https://cloud.githubusercontent.com/assets/7531954/9787208/99f6ba86-57b8-11e5-9651-3b3d00e61254.png)

Is there something prompting for a console input?

**Comment by le-dhogan** [comment]
Also noticed this on a plain command prompt window.

Git version 1.9.5.mysysgit.1
Windows 8 x64

**Comment by m1foley** [comment]
Thanks for reporting -- I haven't tested this in Windows. I'm changing it to use `STDERR` (which is never buffered) instead of `STDOUT`. Hopefully that will fix your issue.

**Comment by m1foley** [comment]
Can you please update (`gem update fit-commit`) and let me know if the issue is fixed?

**Comment by le-dhogan** [comment]
Perfect :+1: thanks.
