### ISSUE TITLE
Option to reopen text editor

### ISSUE THREAD

**Issue by KyleOndy** [m1foley/fit-commit#17]
I do my commits in my preferred $EDITOR. When exiting $EDITOR to commit and fit-commit finds an issue I am forced to retype my commit and try the commit again.

My propsed solution would have an option along the lines of

    Force commit? [y/n/e] 

With e for edit dropping you back into $EDITOR with the incorrect message to make the changes needed.

I am not no handy in ruby or I would hack away at it myself.

**Comment by KyleOndy** [comment]
Perhaps something similar to [this?](https://gist.github.com/jasonrobertfox/8057124#file-validate_commit-rb)

**Comment by m1foley** [comment]
When I've used scripts with that approach, they always seem to lose `STDOUT` when attempting to reopen Vim. That's why I started with the conservative approach here.

I'm leaving this issue open because I'd love to have that feature in the future.

**Comment by dbburgess** [comment]
This is definitely a feature I'd appreciate.

**Comment by m1foley** [comment]
This feature will be there when you `gem update fit-commit`. Let me know if you experience any issues.

**Comment by dbburgess** [comment]
Awesome, it works great @m1foley, thanks! :tada:
