### ISSUE TITLE
Capitalize the subject line

### ISSUE THREAD

**Issue by davidxmoody** [m1foley/fit-commit#19]
Hi, this is an awesome project! Thank you for creating it.

It would be very nice if it also had validation against commit messages not starting with a capital letter though. In my experience, it is usually the thing that is the most inconsistent in other people's commit messages.

It is even recommend as one of the seven rules in the post you linked to: http://chris.beams.io/posts/git-commit/#capitalize

**Comment by m1foley** [comment]
I agree, this validation should be in Fit Commit. Thanks!

**Comment by davidxmoody** [comment]
Thanks for such a quick update :smile:
