### ISSUE TITLE
Unable to use fitcommit with a GUI git client

### ISSUE THREAD

**Issue by scags9876** [m1foley/fit-commit#20]
Using RubyMine, I get the following error when attempting to commit:
```
Error:.git/hooks/commit-msg: line 38: /dev/tty: Device not configured
```

This is the same issue as described here:
http://stackoverflow.com/questions/17930805/github-gui-client-dev-tty-device-not-configured
And so it looks like it affects more than just Rubymine.

It would be nice if there was a non-interactive option, either auto-failing or auto-forcing with a warning in the face of an error, that did not make use of /dev/tty.

**Comment by m1foley** [comment]
Thanks for reporting. I'll download Rubymine and play around with it.

My intuition is to add the following config options:

```yaml
Interactive: true
AlwaysForce: false
```

If `/dev/tty` isn't available, `Interactive` would be `false` regardless of the user's config settings.

**Comment by scags9876** [comment]
Thanks for the swift reply!   Love this little tool by the way.

I got my rubymine to half way work by just removing the `< /dev/tty' in commit-msg, though now it always fails instead of always forcing.   I'd rather it just force with a warning so I can amend if i want to.

**Comment by m1foley** [comment]
Unfortunately, I don't see a way to prompt RubyMine users during Git commits. It also doesn't display warnings unless the process fails.

Looks like this will be an all-or-nothing affair with `Interactive` as described above. It will behave the same as your hack, and the `[y/n]` prompt will be hidden as well.

I'll leave out `AlwaysForce` because I can't think of a realistic scenario for it.

**Comment by m1foley** [comment]
Fit Commit now automatically detects if it is called from outside a terminal. I decided against adding the config vars because I don't see a use case for them.

Try the newest version and let me know if there's more room for improvement: `gem update fit-commit && fit-commit install`
