### ISSUE TITLE
rvm gives warning on commit 

### ISSUE THREAD

**Issue by scags9876** [m1foley/fit-commit#23]
Whenever I do a commit, I get the following warning:
```
$ git commit -m 'test'
Warning! PATH is not properly set up, '/Users/$USER/.rvm/gems/ruby-2.2.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.3'.
```

My path is set up correctly, with the above line appearing first.  However, if I `echo $PATH` from inside the .git/hooks/commit-msg file, i get:
```
/usr/local/Cellar/git/2.5.0/libexec/git-core:/usr/local/Cellar/git/2.5.0/libexec/git-core:/Users/$USER/.rvm/gems/ruby-2.2.3/bin...
```

Digging into this a little more, i found someone else had a very similar issue: https://github.com/rvm/rvm/issues/2347

The suggested solution is to use `ruby-rvm-env` instead of `rvm default do ruby` as the command.  I changed my local commit-msg hook, and it worked! No warning (yey).

If you like, I can submit a pull request to change this in the template.

**Comment by m1foley** [comment]
Thanks for reporting. I see that pre-commit solves this issue by setting [rvm_silence_path_mismatch_check_flag](https://github.com/jish/pre-commit/blob/master/templates/hooks/automatic#L27). I'm not very familiar with rvm -- do you feel that switching to `ruby-rvm-env` is more appropriate?

**Comment by scags9876** [comment]
I'm not very familiar either.  Not sure which is the better option.

**Comment by m1foley** [comment]
Can you confirm that this is fixed for you? `gem update fit-commit && fit-commit install`
