### ISSUE TITLE
server-side support

### ISSUE THREAD

**Issue by aspiers** [m1foley/fit-commit#32]
It's great having client-side validation, but let's face it some developers will simply forget or be too lazy to set it up, and then they'll submit bad commits for review regardless.  So ideally there should be a way to enforce validation server-side.  Of course the implementation depends on the server in question, but GitHub might be a good place to start.  For example might it be possible to create a GitHub third-party service which runs fit-commit server-side whenever a PR is submitted / updated, and then updates a status check on the PR accordingly?

See also [codeclimate/spec#45 (allow analysis of commit messages)](https://github.com/codeclimate/spec/issues/45)

**Comment by aspiers** [comment]
OK, this was basically a stupid question as per https://github.com/jorisroovers/gitlint/issues/19#issuecomment-266602173 - closing :)

**Comment by m1foley** [comment]
Not a stupid question. I'm considering documenting how to run it standalone for use cases like this.

I'd probably do this with a simple shell script on the CI machine. It exits with an error code if any errors are present which should fail the CI build.

```sh
$ GIT_BRANCH_NAME=master COMMIT_MESSAGE_PATH=path/to/message rbenv exec ruby -rrubygems -e 'require "fit_commit"; FitCommit.run'
```

**Comment by aspiers** [comment]
Oh yeah, good idea to document this - thanks! Of course feel free to reopen if you want to track that task :)

**Comment by m1foley** [comment]
Documentation added.
