### ISSUE TITLE
Why exit(1) if runner.run returns falsy?

### ISSUE THREAD

**Issue by bf4** [m1foley/fit-commit#5]
```ruby
  def self.run
    runner.run || exit(1)
  end
```

either runner.run should return the exit code or it should be more clear here why a falsy return is an error.

I'm happy to make a PR to change it, if you'd like.

**Comment by m1foley** [comment]
Agreed, this is cryptic. Do you think this would make it more clear?

```ruby
  def self.run
    allow_commit = runner.run
    exit(1) unless allow_commit
  end
```

**Comment by bf4** [comment]
A common pattern would just be 'exit runner' and runner returns 0 to allow commit. Shrug
>

**Comment by bf4** [comment]
@m1foley here's a nice example :) https://github.com/rails/rails/commit/9946788775437513c3489b7d7b2b01fcda62d5fb#diff-57bbfc787d48a7a6e0353a52719f482a

**Comment by m1foley** [comment]
Yes, thanks. I think it's a tradeoff between succinctness and readability, and I'd prefer to go with the latter in this instance.
